#!/bin/sh
### BEGIN INIT INFO
# Provides:          pi-blaster
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop pi-blaster software PWM for GPIO pins
### END INIT INFO

NAME=pi-blaster
APP_PATH=/home/pi/$NAME

case "$1" in
  start)
    if [ -e /var/lock/$NAME ]
    then 
  		echo "$NAME is already running"
  	else
  		sudo touch /var/lock/$NAME
  		echo "Starting $NAME"
  		sudo $APP_PATH/$NAME
	fi
    ;;
  stop)
    echo "Stopping $NAME"
    sudo rm /var/lock/$NAME
    sudo killall $NAME
    ;;
  status)
        if [ -e /var/lock/$NAME ]
        then
                echo "$NAME is running"
        else
                echo "$NAME is stopped"
        fi
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|status}"
    exit 1
    ;;
esac

exit 0
