#!/bin/sh
### BEGIN INIT INFO
# Provides:          rangeSensor
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop rangeSensor software
### END INIT INFO

NAME=rangeSensor
APP_NAME=rangeSensor.pyc
PLTN_ROOT=/usr/local/pltn
ALL_OFF_PATH=$PLTN_ROOT/Modules/LED
APP_PATH=$PLTN_ROOT/$NAME

case "$1" in
  start)
    if [ -e /var/lock/$NAME ]
    then 
  		echo "$NAME is already running"
  	else
  		sudo touch /var/lock/$NAME
  		echo "Starting $NAME"
  		sudo python $APP_PATH/$APP_NAME
	fi
    ;;
  stop)
    echo "Stopping $NAME"
    sudo rm /var/lock/$NAME
    sudo pkill -9 -f $APP_NAME
    sudo python $ALL_OFF_PATH/allOff.pyc
    ;;
  status)
        if [ -e /var/lock/$NAME ]
        then
                echo "$NAME is running"
        else
                echo "$NAME is stopped"
        fi
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|status}"
    exit 1
    ;;
esac

exit 0
