#!/bin/sh
### BEGIN INIT INFO
# Provides:          rangeSensor
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop rangeSensor software
### END INIT INFO

NAME=rangeSensor
APP_NAME=rangeSensor.py
APP_PATH=/home/pi/projects/platoon/$NAME

case "$1" in
  start)
    sudo touch /var/lock/$NAME
    echo "Starting $NAME"
    sudo $APP_PATH/$APP_NAME
    ;;
  stop)
    echo "Stopping $NAME"
    sudo rm /var/lock/$NAME
    sudo killall $APP_NAME
    ;;
  status)
        if [ -e /var/lock/$NAME ]
        then
                echo "$NAME is running"
        else
                echo "$NAME is stopped"
        fi
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|status}"
    exit 1
    ;;
esac

exit 0
